// Risky FMRA demo module — loaded after app.js
const fmraDemo=[
 {id:'FMRA-2026-084',date:'20/08/2026',site:'Jumet',activity:'Maintenance groupe frigorifique',worker:'Équipe HVAC',status:'GO',checks:6},
 {id:'FMRA-2026-083',date:'20/08/2026',site:'LLN',activity:'Intervention tableau BT',worker:'Équipe Électricité',status:'NO-GO',checks:4}
];
function fmraPage(){return `<div class="fmra-page"><div class="module-title"><div><div class="eyebrow fmra-green">FMRA</div><h2>Field / Last Minute Risk Assessment</h2><p class="muted">Évaluation dynamique des risques avant le début du travail.</p></div><button class="btn fmra-btn" onclick="newFmra()">+ Nouvelle FMRA</button></div><div class="fmra-kpis"><div class="card"><span>FMRA aujourd’hui</span><strong>${fmraDemo.length}</strong></div><div class="card"><span>Décisions GO</span><strong>${fmraDemo.filter(x=>x.status==='GO').length}</strong></div><div class="card"><span>NO-GO / STOP</span><strong class="fmra-red">${fmraDemo.filter(x=>x.status==='NO-GO').length}</strong></div></div><div class="card fmra-list"><div class="fmra-list-head"><b>FMRA récentes</b><span>La décision finale reste visible dans le registre.</span></div>${fmraDemo.map(f=>`<div class="row"><span><b>${f.id}</b> · ${f.activity}<br><span class="muted">${f.date} · ${f.site} · ${f.worker}</span></span><span class="fmra-status ${f.status==='GO'?'go':'nogo'}">${f.status}</span></div>`).join('')}</div></div>`}
function newFmra(){document.querySelector('#content').innerHTML=`<div class="fmra-page"><div class="event-head"><div><div class="eyebrow fmra-green">FMRA terrain</div><h2>Évaluation avant démarrage</h2><p>Observer → vérifier → décider GO / NO-GO.</p></div><div class="info-banner fmra-info"><span class="info-dot fmra-i">i</span><span>La FMRA ne remplace pas l’analyse de risques. Elle vérifie que les conditions réelles permettent de commencer ou poursuivre le travail en sécurité.</span></div></div><section class="card fmra-context"><div class="grid2"><label>Activité / intervention <b>*</b><input id="factivity" value="Maintenance groupe frigorifique"></label><label>Site <b>*</b><select id="fsite"><option>Jumet</option><option>Louvain-la-Neuve</option><option>Alleur</option></select></label><label>Équipe / intervenant <b>*</b><input id="fworker" value="Équipe HVAC"></label><label>Zone / chantier<input id="fzone" value="Toiture technique"></label></div></section><div class="fmra-columns"><section class="card fmra-checks"><div class="section-title fmra-title"><span>✓</span><h3>Vérifications avant travail</h3></div>${fmraCheck('f1','Je connais le travail à réaliser et les consignes applicables.')}${fmraCheck('f2','Les énergies dangereuses sont identifiées et maîtrisées.')}${fmraCheck('f3','Les accès, la zone de travail et les protections collectives sont sûrs.')}${fmraCheck('f4','Les outils, équipements et EPI nécessaires sont disponibles et adaptés.')}${fmraCheck('f5','Les produits / fluides et leurs risques sont connus et maîtrisés.')}${fmraCheck('f6','Je peux réaliser ce travail sans créer de risque pour moi ou pour les autres.')}</section><section class="card fmra-decision"><div class="section-title fmra-title"><span>!</span><h3>Décision terrain</h3></div><label>Danger ou changement constaté<textarea id="fremark" rows="5" placeholder="Décrire ici toute condition particulière, changement ou risque observé…"></textarea></label><div class="decision-help"><b>Un doute = pas de démarrage.</b><span>En cas de NO-GO, le travail est suspendu jusqu’à mise en place d’une solution sûre.</span></div><div class="decision-buttons"><button class="decision go" onclick="saveFmra('GO')"><strong>✓ GO</strong><span>Conditions maîtrisées</span></button><button class="decision nogo" onclick="saveFmra('NO-GO')"><strong>✕ NO-GO</strong><span>Travail suspendu</span></button></div></section></div><div class="event-actions"><button class="btn secondary" onclick="show('fmra',document.querySelector('[data-page=fmra]'))">Annuler</button></div></div>`}
function fmraCheck(id,text){return `<label class="fmra-check"><input type="checkbox" id="${id}" checked><span><b>${text}</b><small>Vérifié sur le terrain avant démarrage</small></span></label>`}
function saveFmra(status){const checked=['f1','f2','f3','f4','f5','f6'].filter(id=>document.getElementById(id).checked).length;if(status==='GO'&&checked<6){alert('Une décision GO nécessite la validation de toutes les vérifications. Corrigez la situation ou choisissez NO-GO.');return}fmraDemo.unshift({id:`FMRA-2026-${String(85+fmraDemo.length).padStart(3,'0')}`,date:'20/08/2026',site:fsite.value,activity:factivity.value,worker:fworker.value,status,checks:checked});show('fmra',document.querySelector('[data-page=fmra]'))}
const riskyBaseShow=show;show=function(p,b){if(p==='fmra'){document.querySelectorAll('.navitem').forEach(x=>x.classList.remove('active'));b?.classList.add('active');document.querySelector('#title').textContent='FMRA';document.querySelector('#content').innerHTML=fmraPage();return}return riskyBaseShow(p,b)};
