// Risky document library, form builder and quality demo
const docsDemo=[
{id:'DOC-001',title:'Procédure de consignation électrique',cat:'Procédure',version:'3.2',owner:'SIPP',review:'15/01/2027',status:'Publié',site:'Tous les sites'},
{id:'DOC-002',title:'Instruction travail en hauteur',cat:'Instruction',version:'2.1',owner:'QHSE',review:'04/11/2026',status:'Publié',site:'Tous les sites'},
{id:'DOC-003',title:'Analyse de risques — intervention toiture',cat:'Analyse de risques',version:'1.4',owner:'SIPP',review:'22/09/2026',status:'À réviser',site:'Jumet'},
{id:'DOC-004',title:'Plan d’urgence environnemental',cat:'Plan',version:'1.0',owner:'QHSE',review:'12/03/2027',status:'Publié',site:'LLN'}];
const formsDemo=[
{id:'FOR-001',title:'Contrôle échafaudage roulant',fields:14,uses:38,status:'Actif'},
{id:'FOR-002',title:'Accueil sécurité chantier',fields:11,uses:126,status:'Actif'},
{id:'FOR-003',title:'Contrôle trousse de secours',fields:9,uses:24,status:'Actif'}];
const qualityDemo=[{label:'Réclamations ouvertes',value:'3',note:'−2 vs mois précédent'},{label:'Non-conformités',value:'7',note:'2 critiques'},{label:'Actions clôturées à temps',value:'91%',note:'Objectif 90%'},{label:'Audits réalisés',value:'8 / 10',note:'Année 2026'}];
function documentsPage(){return `<div class="library-page"><div class="module-title"><div><div class="eyebrow doc-blue">GED QHSE</div><h2>Documents</h2><p class="muted">Bibliothèque documentaire, versions, propriétaires et échéances de révision.</p></div><button class="btn">+ Ajouter un document</button></div><div class="library-kpis"><div class="card"><span>Documents actifs</span><strong>89</strong></div><div class="card"><span>À réviser &lt; 90 j</span><strong class="warn">6</strong></div><div class="card"><span>En retard</span><strong class="bad">2</strong></div><div class="card"><span>Catégories</span><strong>12</strong></div></div><div class="library-toolbar card"><input placeholder="⌕ Rechercher un document, une référence…"><select><option>Toutes les catégories</option><option>Procédure</option><option>Instruction</option><option>Analyse de risques</option></select><select><option>Tous les sites</option><option>Jumet</option><option>LLN</option><option>Alleur</option></select></div><div class="card doc-table"><div class="doc-head"><span>Document</span><span>Version</span><span>Propriétaire</span><span>Révision</span><span>Statut</span></div>${docsDemo.map(d=>`<div class="doc-row"><span><b>${d.title}</b><small>${d.id} · ${d.cat} · ${d.site}</small></span><span>v${d.version}</span><span>${d.owner}</span><span>${d.review}</span><span class="status-chip ${d.status==='À réviser'?'late':'doing'}">${d.status}</span></div>`).join('')}</div><div class="doc-note">Dans la version complète, un document pourra être relié aux fiches 360° personne, équipement, site, analyse de risques ou action.</div></div>`}
function formsPage(){return `<div class="library-page"><div class="module-title"><div><div class="eyebrow form-purple">No-code QHSE</div><h2>Formulaires</h2><p class="muted">Créer des formulaires internes sans modifier le code de Risky.</p></div><button class="btn purple" onclick="newFormDemo()">+ Nouveau formulaire</button></div><div class="builder-layout"><section class="card"><h3>Bibliothèque de formulaires</h3>${formsDemo.map(f=>`<button class="form-item"><span><b>${f.title}</b><small>${f.id} · ${f.fields} champs · ${f.uses} réponses</small></span><span class="status-chip doing">${f.status}</span></button>`).join('')}</section><section class="card builder-preview"><div class="builder-title"><div><h3>Constructeur de formulaire</h3><p>Exemple : inspection interne simple</p></div><span class="draft-chip">BROUILLON</span></div><label>Titre du formulaire<input value="Visite sécurité atelier"></label><div class="field-palette"><button>＋ Texte</button><button>＋ Oui / Non</button><button>＋ Liste</button><button>＋ Date</button><button>＋ Photo</button><button>＋ Signature</button></div><div class="form-canvas"><div class="canvas-field"><span class="drag">⋮⋮</span><div><b>Zone contrôlée</b><small>Champ texte · obligatoire</small></div><button>⋯</button></div><div class="canvas-field"><span class="drag">⋮⋮</span><div><b>Situation conforme ?</b><small>Oui / Non · obligatoire</small></div><button>⋯</button></div><div class="canvas-field"><span class="drag">⋮⋮</span><div><b>Photo / preuve</b><small>Photo · optionnel</small></div><button>⋯</button></div></div><div class="builder-actions"><button class="btn secondary">Aperçu</button><button class="btn purple">Publier le formulaire</button></div></section></div></div>`}
function newFormDemo(){alert('Démo : le constructeur permettra d’ajouter, ordonner et paramétrer les champs sans développement.')}
function qualityPage(){return `<div class="library-page"><div class="module-title"><div><div class="eyebrow quality-teal">Qualité</div><h2>Pilotage qualité</h2><p class="muted">Non-conformités, réclamations, audits et amélioration continue.</p></div><button class="btn teal">+ Nouvelle non-conformité</button></div><div class="library-kpis">${qualityDemo.map((k,i)=>`<div class="card"><span>${k.label}</span><strong class="${i===1?'bad':''}">${k.value}</strong><small>${k.note}</small></div>`).join('')}</div><div class="quality-grid"><section class="card"><h3>Non-conformités récentes</h3>${[['NC-2026-018','Écart documentaire sur dossier chantier','Mineure','En traitement'],['NC-2026-017','Matériel livré non conforme au cahier des charges','Majeure','Action ouverte'],['NC-2026-016','Traçabilité contrôle final incomplète','Mineure','Clôturée']].map(n=>`<div class="quality-line"><span><b>${n[0]} · ${n[1]}</b><small>${n[2]}</small></span><span class="status-chip ${n[3]==='Clôturée'?'doing':'late'}">${n[3]}</span></div>`).join('')}</section><section class="card"><h3>Performance qualité — 2026</h3><div class="quality-score"><strong>91%</strong><span>Actions clôturées dans le délai</span></div><div class="progress"><i style="width:91%"></i></div>${[['Satisfaction client','94%'],['Clôture NC < 30 jours','86%'],['Audits planifiés réalisés','80%']].map(x=>`<div class="metric"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</section></div><section class="card quality-bottom"><h3>Logique intégrée Risky</h3><p>Une non-conformité peut générer une action dans le plan global, être rattachée à un site, un équipement ou un document, puis être suivie jusqu’à vérification de l’efficacité.</p></section></div>`}
const libraryBaseShow=show;show=function(p,b){if(['documents','forms','quality'].includes(p)){document.querySelectorAll('.navitem').forEach(x=>x.classList.remove('active'));b?.classList.add('active');document.querySelector('#title').textContent=p==='documents'?'Documents':p==='forms'?'Formulaires':'Qualité';document.querySelector('#content').innerHTML=p==='documents'?documentsPage():p==='forms'?formsPage():qualityPage();return}return libraryBaseShow(p,b)};