// Risky management modules — Plan d’actions, Compétences, fiches 360°
const riskyActions = demo.actions;
riskyActions.forEach((a,i)=>{
  if(a.annual===undefined) a.annual = i===0;
  if(a.cppt===undefined) a.cppt = i===1;
  if(!a.year) a.year = 2026;
  if(!a.progress) a.progress = a.status==='En cours'?50:20;
});
riskyActions.push(
 {id:'A-2026-040',title:'Actualiser la procédure travail en hauteur',source:'CPPT 06/2026',site:'Jumet',owner:'Responsable SIPP',due:'30/09/2026',priority:'Haute',status:'En cours',annual:true,cppt:true,year:2026,progress:60},
 {id:'A-2026-041',title:'Déployer le contrôle trimestriel des échelles',source:'Plan annuel',site:'Tous sites',owner:'QHSE Officer',due:'15/10/2026',priority:'Moyenne',status:'À traiter',annual:true,cppt:false,year:2026,progress:15},
 {id:'A-2026-042',title:'Clôturer l’action issue du CPPT de mai',source:'CPPT 05/2026',site:'LLN',owner:'Site Supervisor',due:'15/08/2026',priority:'Haute',status:'En retard',annual:false,cppt:true,year:2026,progress:80}
);

const competenceCatalog=['BA5','Cariste / Clark','Nacelle élévatrice','Manitou / télescopique','Montage échafaudage','Travail en hauteur','Espaces confinés','Secouriste'];
const peopleDemo=[
 {id:'P-001',name:'Pierre Lambert',role:'Chef d’équipe Électricité',site:'Jumet',skills:{'BA5':['Valide','12/03/2028'],'Nacelle élévatrice':['Valide','05/11/2027'],'Travail en hauteur':['Valide','18/06/2027'],'Secouriste':['À renouveler','02/10/2026']}},
 {id:'P-002',name:'Julien Martin',role:'Technicien HVAC',site:'LLN',skills:{'BA5':['Non requis','—'],'Manitou / télescopique':['Valide','09/04/2027'],'Travail en hauteur':['Valide','14/01/2028'],'Espaces confinés':['Expiré','30/06/2026']}},
 {id:'P-003',name:'Sophie Renard',role:'Site Supervisor',site:'Alleur',skills:{'BA5':['Valide','21/02/2028'],'Cariste / Clark':['Valide','13/12/2027'],'Montage échafaudage':['Valide','08/05/2027'],'Secouriste':['Valide','17/03/2028']}}
];

let actionView='global';
function actionPlanPage(view='global'){
 actionView=view;
 const rows = view==='annual'?riskyActions.filter(a=>a.annual):view==='cppt'?riskyActions.filter(a=>a.cppt):riskyActions;
 const title=view==='global'?'Plan d’actions global':view==='annual'?'Plan annuel d’action':'Suivi CPPT';
 const sub=view==='global'?'Toutes les actions générées ou saisies dans Risky.':view==='annual'?'Vue des actions intégrées au plan annuel.':'Décisions et actions suivies en CPPT.';
 return `<div class="mgmt-page"><div class="module-title"><div><div class="eyebrow risk-blue">Pilotage</div><h2>${title}</h2><p class="muted">${sub}</p></div><button class="btn" onclick="newGlobalAction()">+ Nouvelle action</button></div>
 <div class="action-tabs"><button class="${view==='global'?'active':''}" onclick="renderActionView('global')">Global <span>${riskyActions.length}</span></button><button class="${view==='annual'?'active':''}" onclick="renderActionView('annual')">Plan annuel <span>${riskyActions.filter(a=>a.annual).length}</span></button><button class="${view==='cppt'?'active':''}" onclick="renderActionView('cppt')">CPPT <span>${riskyActions.filter(a=>a.cppt).length}</span></button></div>
 <div class="mgmt-kpis"><div class="card"><span>Ouvertes</span><strong>${rows.filter(a=>a.status!=='Clôturée').length}</strong></div><div class="card"><span>En retard</span><strong class="bad">${rows.filter(a=>a.status==='En retard').length}</strong></div><div class="card"><span>Avancement moyen</span><strong>${rows.length?Math.round(rows.reduce((s,a)=>s+a.progress,0)/rows.length):0}%</strong></div></div>
 <div class="card action-table"><div class="table-head"><span>Action</span><span>Responsable</span><span>Échéance</span><span>Avancement</span><span>Statut</span></div>${rows.map(a=>actionRow(a)).join('')}</div></div>`;
}
function actionRow(a){return `<div class="table-row clickable" onclick="openAction('${a.id}')"><span><b>${a.id}</b> · ${a.title}<small>Source : ${a.source} · ${a.site}${a.annual?' · PAA '+a.year:''}${a.cppt?' · CPPT':''}</small></span><span>${a.owner}</span><span>${a.due}</span><span><div class="progress"><i style="width:${a.progress}%"></i></div><small>${a.progress}%</small></span><span class="status-chip ${a.status==='En retard'?'late':a.status==='En cours'?'doing':''}">${a.status}</span></div>`}
function renderActionView(view){document.querySelector('#content').innerHTML=actionPlanPage(view)}
function openAction(id){const a=riskyActions.find(x=>x.id===id);if(!a)return;document.querySelector('#content').innerHTML=`<div class="mgmt-page"><div class="identity-head"><button class="back-link" onclick="renderActionView('${actionView}')">← Retour</button><div><div class="eyebrow risk-blue">${a.id}</div><h2>${a.title}</h2><p>${a.source} · ${a.site}</p></div><span class="status-chip ${a.status==='En retard'?'late':'doing'}">${a.status}</span></div><div class="identity-grid"><section class="card"><h3>Pilotage</h3>${detail('Responsable',a.owner)}${detail('Échéance',a.due)}${detail('Priorité',a.priority)}${detail('Avancement',a.progress+' %')}</section><section class="card"><h3>Classement</h3>${detail('Plan annuel',a.annual?'Oui — '+a.year:'Non')}${detail('CPPT',a.cppt?'Oui':'Non')}${detail('Source',a.source)}${detail('Site',a.site)}</section></div><section class="card identity-section"><h3>Suivi de l’action</h3><div class="progress big"><i style="width:${a.progress}%"></i></div><p class="muted">Cette fiche 360° pourra ensuite accueillir les commentaires, preuves de clôture, pièces jointes et historique des modifications.</p></section></div>`}
function newGlobalAction(){alert('Le formulaire de création complet sera branché dans l’étape suivante. Les vues Global / Plan annuel / CPPT sont déjà liées au même moteur d’actions.')}
function detail(k,v){return `<div class="detail"><span>${k}</span><b>${v}</b></div>`}

function competenciesPage(){return `<div class="mgmt-page"><div class="module-title"><div><div class="eyebrow competency-purple">Compétences</div><h2>Registre des compétences à risques</h2><p class="muted">Habilitations, formations et autorisations nécessaires aux tâches à risques.</p></div><button class="btn purple">+ Ajouter une personne</button></div><div class="mgmt-kpis"><div class="card"><span>Personnes suivies</span><strong>${peopleDemo.length}</strong></div><div class="card"><span>Compétences suivies</span><strong>${competenceCatalog.length}</strong></div><div class="card"><span>À renouveler / expirées</span><strong class="bad">${peopleDemo.reduce((n,p)=>n+Object.values(p.skills).filter(x=>x[0]==='Expiré'||x[0]==='À renouveler').length,0)}</strong></div></div><div class="card matrix-wrap"><div class="matrix"><div class="matrix-head"><span>Personne</span>${competenceCatalog.map(c=>`<span>${c}</span>`).join('')}</div>${peopleDemo.map(p=>`<div class="matrix-row"><button onclick="openPerson('${p.id}')"><b>${p.name}</b><small>${p.role}<br>${p.site}</small></button>${competenceCatalog.map(c=>skillCell(p.skills[c])).join('')}</div>`).join('')}</div></div></div>`}
function skillCell(s){if(!s)return `<span class="skill none">—</span>`;const cls=s[0]==='Valide'?'valid':s[0]==='Expiré'?'expired':s[0]==='À renouveler'?'renew':'na';return `<span class="skill ${cls}"><b>${s[0]}</b><small>${s[1]}</small></span>`}
function openPerson(id){const p=peopleDemo.find(x=>x.id===id);if(!p)return;const assigned=riskyActions.filter(a=>a.owner.toLowerCase().includes(p.name.split(' ')[1].toLowerCase())||a.owner.toLowerCase().includes(p.name.split(' ')[0].toLowerCase()));document.querySelector('#content').innerHTML=`<div class="mgmt-page"><div class="identity-head"><button class="back-link" onclick="show('people',document.querySelector('[data-page=people]'))">← Retour</button><div class="identity-avatar">${p.name.split(' ').map(x=>x[0]).join('')}</div><div><div class="eyebrow competency-purple">Fiche 360° personne</div><h2>${p.name}</h2><p>${p.role} · ${p.site}</p></div></div><div class="identity-grid"><section class="card"><h3>Compétences à risques</h3>${Object.entries(p.skills).map(([k,v])=>`<div class="identity-skill"><span>${k}</span>${skillCell(v)}</div>`).join('')}</section><section class="card"><h3>Activité dans Risky</h3>${detail('Actions attribuées',assigned.length)}${detail('FMRA liées','4')}${detail('Toolbox suivies','7')}${detail('Événements associés','0')}</section></div><section class="card identity-section"><div class="section-title"><span>◎</span><h3>Vue transversale</h3></div><p class="muted">Cette fiche regroupe tout ce que Risky connaît sur cette personne : compétences, échéances, FMRA, Toolbox, actions, événements et futurs documents associés.</p></section></div>`}

const mgmtBaseShow=show;
show=function(p,b){if(p==='actions'){document.querySelectorAll('.navitem').forEach(x=>x.classList.remove('active'));b?.classList.add('active');document.querySelector('#title').textContent='Plan d’actions';document.querySelector('#content').innerHTML=actionPlanPage('global');return}if(p==='people'){document.querySelectorAll('.navitem').forEach(x=>x.classList.remove('active'));b?.classList.add('active');document.querySelector('#title').textContent='Compétences';document.querySelector('#content').innerHTML=competenciesPage();return}return mgmtBaseShow(p,b)};
