// Transversal demo relationships — illustrates the future shared QHSE data model
const relationDemo={
 event:{id:'AT-2026-007',title:'Entorse du poignet lors d’une intervention',date:'20/08/2026',site:'Jumet',person:'P-001',risk:'AR-2026-015',action:'A-2026-040',equipment:'EQ-001',status:'En analyse'},
 person:'P-001',risk:'AR-2026-015',action:'A-2026-040',equipment:'EQ-001'
};
function relationButton(icon,label,value,onclick,cls=''){return `<button class="relation-card ${cls}" onclick="${onclick}"><span>${icon}</span><div><small>${label}</small><b>${value}</b></div><em>→</em></button>`}
function openLinkedRisk(id){riskyGo('risks');setTimeout(()=>{const c=document.querySelector('#content');if(c)c.insertAdjacentHTML('afterbegin',`<div class="linked-focus">Lien ouvert depuis une autre fiche Risky · <b>${id}</b></div>`)},0)}
function openLinkedEquipment(id){const e=typeof equipmentDemo!=='undefined'&&equipmentDemo.find(x=>x.id===id);if(e){riskyGo('equipment');setTimeout(()=>openEquipment(id),0)}}
function openLinkedAction(id){riskyGo('actions');setTimeout(()=>openAction(id),0)}
function openLinkedPerson(id){riskyGo('people');setTimeout(()=>openPerson(id),0)}
function linkedAccidentRegister(){const e=relationDemo.event;return `<div class="stats-page"><div class="module-title"><div><div class="eyebrow">Accidents & Incidents</div><h2>Registre des événements</h2><p class="muted">Exemple de dossier transversal reliant les informations déjà présentes dans Risky.</p></div><button class="btn danger" onclick="newEvent()">+ Déclarer un événement</button></div><div class="stats-tabs"><button onclick="document.querySelector('#content').innerHTML=accidentsStatsPage()">Statistiques</button><button class="active">Registre des événements</button></div><div class="card relation-event-list"><button class="relation-event" onclick="openEvent360('${e.id}')"><span class="event-icon">⚠</span><span><b>${e.id} · ${e.title}</b><small>${e.date} · ${e.site} · Dossier transversal de démonstration</small><i><u>Personne liée</u> · <u>Analyse de risques</u> · <u>Action</u> · <u>Équipement</u></i></span><span class="status-chip doing">${e.status}</span><em>→</em></button>${demo.events.filter(x=>x.id!==e.id).map(x=>`<div class="relation-event plain"><span class="event-icon">○</span><span><b>${x.id} · ${x.title}</b><small>${x.date} · ${x.site}</small></span><span class="status-chip ${x.status==='Clôturé'?'done':'doing'}">${x.status}</span></div>`).join('')}</div></div>`}
accidents=linkedAccidentRegister;
function openEvent360(id){const e=relationDemo.event;if(id!==e.id)return;const p=peopleDemo.find(x=>x.id===e.person),r=demo.risks.find(x=>x.id===e.risk),a=riskyActions.find(x=>x.id===e.action),eq=equipmentDemo.find(x=>x.id===e.equipment);document.querySelector('#content').innerHTML=`<div class="relation-page"><button class="back-link" onclick="document.querySelector('#content').innerHTML=accidents()">← Retour au registre</button><div class="relation-hero card"><div class="relation-big-icon">⚠</div><div><div class="eyebrow">Fiche 360° événement</div><h2>${e.id} · ${e.title}</h2><p>${e.date} · ${e.site}</p></div><span class="status-chip doing">${e.status}</span></div><div class="identity-grid"><section class="card"><h3>Événement</h3>${detail('Type','Accident avec arrêt')}${detail('Personne concernée',p?.name||'—')}${detail('Jours perdus','6')}${detail('Statut',e.status)}</section><section class="card"><h3>Analyse & suivi</h3>${detail('Danger principal','Chute / intervention technique')}${detail('Analyse liée',r?.id||e.risk)}${detail('Action corrective',a?.id||e.action)}${detail('Équipement lié',eq?.ref||e.equipment)}</section></div><section class="card relation-network"><div class="section-title"><span>⤨</span><h3>Relations dans Risky</h3></div><p class="muted">Un même événement alimente plusieurs modules sans ressaisie. Cliquez sur une relation pour ouvrir la fiche correspondante.</p><div class="relation-grid">${relationButton('♙','Personne',p?.name||e.person,`openLinkedPerson('${e.person}')`,'person')}${relationButton('◇','Analyse de risques',r?.title||e.risk,`openLinkedRisk('${e.risk}')`,'risk')}${relationButton('☑','Action corrective',a?.title||e.action,`openLinkedAction('${e.action}')`,'action')}${relationButton('▣','Équipement',eq?.name||e.equipment,`openLinkedEquipment('${e.equipment}')`,'equipment')}</div></section><section class="card relation-timeline"><h3>Historique du dossier</h3><div><b>20/08/2026 · 09:12</b><span>Événement déclaré dans Risky</span></div><div><b>20/08/2026 · 10:05</b><span>Analyse de risques associée au dossier</span></div><div><b>20/08/2026 · 11:20</b><span>Action corrective créée et attribuée</span></div><div><b>21/08/2026</b><span>Suivi SIPP en cours</span></div></section></div>`}
// Enrich the existing person 360° page with relations for the demonstration person.
const relationBaseOpenPerson=openPerson;openPerson=function(id){relationBaseOpenPerson(id);if(id!==relationDemo.person)return;const c=document.querySelector('#content .mgmt-page');if(!c)return;const r=demo.risks.find(x=>x.id===relationDemo.risk),a=riskyActions.find(x=>x.id===relationDemo.action),eq=equipmentDemo.find(x=>x.id===relationDemo.equipment);c.insertAdjacentHTML('beforeend',`<section class="card relation-network"><div class="section-title"><span>⤨</span><h3>Relations actives dans Risky</h3></div><div class="relation-grid">${relationButton('⚠','Événement','AT-2026-007',`openEvent360('AT-2026-007')`,'event')}${relationButton('◇','Analyse',r?.id||relationDemo.risk,`openLinkedRisk('${relationDemo.risk}')`,'risk')}${relationButton('☑','Action',a?.id||relationDemo.action,`openLinkedAction('${relationDemo.action}')`,'action')}${relationButton('▣','Équipement',eq?.ref||relationDemo.equipment,`openLinkedEquipment('${relationDemo.equipment}')`,'equipment')}</div></section>`)};
// Enrich the action 360° page with a visible source relation.
const relationBaseOpenAction=openAction;openAction=function(id){relationBaseOpenAction(id);if(id!==relationDemo.action)return;const c=document.querySelector('#content .mgmt-page');if(!c)return;c.insertAdjacentHTML('beforeend',`<section class="card relation-network"><div class="section-title"><span>⤨</span><h3>Origine et relations</h3></div><div class="relation-grid">${relationButton('⚠','Événement source',relationDemo.event.id,`openEvent360('${relationDemo.event.id}')`,'event')}${relationButton('♙','Personne concernée','Pierre Lambert',`openLinkedPerson('${relationDemo.person}')`,'person')}${relationButton('◇','Analyse associée',relationDemo.risk,`openLinkedRisk('${relationDemo.risk}')`,'risk')}</div></section>`)};