"""add just culture root node

Revision ID: 0e2603df2e8d
Revises: a6065324834c
Create Date: 2026-09-02 14:56:45.036340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e2603df2e8d'
down_revision: Union[str, Sequence[str], None] = 'a6065324834c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('just_culture_tree_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('root_node_code', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('just_culture_tree_versions', schema=None) as batch_op:
        batch_op.drop_column('root_node_code')

    # ### end Alembic commands ###
