"""add person competency status history

Revision ID: 26a3e27a8677
Revises: 1969add6b56b
Create Date: 2026-08-27 17:30:54.261410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26a3e27a8677'
down_revision: Union[str, Sequence[str], None] = '1969add6b56b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_competency_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_competency_id', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['person_competency_id'], ['person_competencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_competency_status_history')
    # ### end Alembic commands ###
