"""add event facts

Revision ID: 37c27ad91787
Revises: 4ec5ebd7a768
Create Date: 2026-09-01 16:52:12.489846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37c27ad91787'
down_revision: Union[str, Sequence[str], None] = '4ec5ebd7a768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('client', sa.String(length=250), nullable=True),
    sa.Column('worksite', sa.String(length=250), nullable=True),
    sa.Column('project_manager', sa.String(length=250), nullable=True),
    sa.Column('site_supervisor', sa.String(length=250), nullable=True),
    sa.Column('team_leader', sa.String(length=250), nullable=True),
    sa.Column('witnesses', sa.String(length=2000), nullable=True),
    sa.Column('usual_position', sa.Boolean(), nullable=True),
    sa.Column('temporary_worker', sa.Boolean(), nullable=True),
    sa.Column('resumed_same_day', sa.Boolean(), nullable=True),
    sa.Column('activity_before_event', sa.String(length=2000), nullable=True),
    sa.Column('event_description', sa.String(length=4000), nullable=True),
    sa.Column('direct_cause', sa.String(length=2000), nullable=True),
    sa.Column('caused_by_third_party', sa.Boolean(), nullable=True),
    sa.Column('third_party_details', sa.String(length=2000), nullable=True),
    sa.Column('police_report', sa.Boolean(), nullable=True),
    sa.Column('material_damage', sa.Boolean(), nullable=True),
    sa.Column('material_damage_details', sa.String(length=2000), nullable=True),
    sa.Column('environmental_damage', sa.Boolean(), nullable=True),
    sa.Column('environmental_damage_details', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_facts_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_event_facts_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_facts_id'))
        batch_op.drop_index(batch_op.f('ix_event_facts_event_id'))

    op.drop_table('event_facts')
    # ### end Alembic commands ###
