"""refine serious accident criteria

Revision ID: 3c948877ece3
Revises: e43c1ad31e12
Create Date: 2026-09-01 14:15:29.752077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c948877ece3'
down_revision: Union[str, Sequence[str], None] = 'e43c1ad31e12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serious_accident_criteria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('code_from', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('code_to', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('requires_multiple_lost_days', sa.Boolean(), nullable=False))
        batch_op.drop_column('code')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serious_accident_criteria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('requires_multiple_lost_days')
        batch_op.drop_column('code_to')
        batch_op.drop_column('code_from')
        batch_op.drop_column('match_type')

    # ### end Alembic commands ###
