"""add cause fact terminal status

Revision ID: 3cd7cec6a10f
Revises: d73ec9d1ef7a
Create Date: 2026-09-03 10:27:21.043143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cd7cec6a10f'
down_revision: Union[str, Sequence[str], None] = 'd73ec9d1ef7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table(
        'event_cause_facts',
        schema=None,
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                'is_terminal',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_cause_facts', schema=None) as batch_op:
        batch_op.drop_column('is_terminal')

    # ### end Alembic commands ###
