"""add serious accident rules

Revision ID: 480539a390dc
Revises: 78a1e60f2434
Create Date: 2026-09-01 12:17:19.680822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '480539a390dc'
down_revision: Union[str, Sequence[str], None] = '78a1e60f2434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serious_accident_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('deviation_code', sa.String(length=20), nullable=True),
    sa.Column('material_agent_code', sa.String(length=20), nullable=True),
    sa.Column('injury_nature_code', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('serious_accident_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_serious_accident_rules_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serious_accident_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_serious_accident_rules_id'))

    op.drop_table('serious_accident_rules')
    # ### end Alembic commands ###
