"""add person initials

Revision ID: 49c2e3e93e11
Revises: eb3c860ae576
Create Date: 2026-08-31 11:27:39.805912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49c2e3e93e11'
down_revision: Union[str, Sequence[str], None] = 'eb3c860ae576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initials', sa.String(length=10), nullable=True))
        batch_op.create_index(batch_op.f('ix_people_initials'), ['initials'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_initials'))
        batch_op.drop_column('initials')

    # ### end Alembic commands ###
