"""add modified duty to events

Revision ID: 5380c8f3706d
Revises: 3cd7cec6a10f
Create Date: 2026-09-08 12:10:24.112056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5380c8f3706d'
down_revision: Union[str, Sequence[str], None] = '3cd7cec6a10f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'modified_duty',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.add_column(
            sa.Column(
                'modified_duty_days',
                sa.Integer(),
                nullable=False,
                server_default='0',
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('modified_duty_days')
        batch_op.drop_column('modified_duty')

    # ### end Alembic commands ###
