"""add event analysis type

Revision ID: 637aa92ef332
Revises: 37c27ad91787
Create Date: 2026-09-01 17:22:21.402440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '637aa92ef332'
down_revision: Union[str, Sequence[str], None] = '37c27ad91787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'analysis_type',
                sa.String(length=30),
                nullable=False,
                server_default='NORMAL',
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('analysis_type')

    # ### end Alembic commands ###
