"""add heepo factors

Revision ID: 78a1e60f2434
Revises: 7b52259d911b
Create Date: 2026-09-01 11:39:04.054173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78a1e60f2434'
down_revision: Union[str, Sequence[str], None] = '7b52259d911b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heepo_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family', sa.String(length=30), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('heepo_factors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_heepo_factors_family'), ['family'], unique=False)
        batch_op.create_index(batch_op.f('ix_heepo_factors_id'), ['id'], unique=False)

    op.create_table('event_heepo_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('heepo_factor_id', sa.Integer(), nullable=True),
    sa.Column('family', sa.String(length=30), nullable=False),
    sa.Column('factor_code_snapshot', sa.String(length=50), nullable=True),
    sa.Column('factor_label_snapshot', sa.String(), nullable=True),
    sa.Column('other_text', sa.String(), nullable=True),
    sa.Column('is_na', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['heepo_factor_id'], ['heepo_factors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_heepo_factors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_heepo_factors_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_heepo_factors_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_heepo_factors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_heepo_factors_id'))
        batch_op.drop_index(batch_op.f('ix_event_heepo_factors_event_id'))

    op.drop_table('event_heepo_factors')
    with op.batch_alter_table('heepo_factors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_heepo_factors_id'))
        batch_op.drop_index(batch_op.f('ix_heepo_factors_family'))

    op.drop_table('heepo_factors')
    # ### end Alembic commands ###
