"""add event code references

Revision ID: 79e96ce6eb08
Revises: 5b79d141853c
Create Date: 2026-08-28 11:18:58.705452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79e96ce6eb08'
down_revision: Union[str, Sequence[str], None] = '5b79d141853c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_code_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=1000), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_code_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_code_references_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_code_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_code_references_category'))

    op.drop_table('event_code_references')
    # ### end Alembic commands ###
