"""add event classifications

Revision ID: 7b52259d911b
Revises: c55782fe76e8
Create Date: 2026-09-01 11:04:16.070453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b52259d911b'
down_revision: Union[str, Sequence[str], None] = 'c55782fe76e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('deviation_code', sa.String(length=20), nullable=True),
    sa.Column('deviation_label_snapshot', sa.String(), nullable=True),
    sa.Column('material_agent_code', sa.String(length=20), nullable=True),
    sa.Column('material_agent_label_snapshot', sa.String(), nullable=True),
    sa.Column('injury_nature_code', sa.String(length=20), nullable=True),
    sa.Column('injury_nature_label_snapshot', sa.String(), nullable=True),
    sa.Column('injury_location_code', sa.String(length=20), nullable=True),
    sa.Column('injury_location_label_snapshot', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_classifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_classifications_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_event_classifications_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_classifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_classifications_id'))
        batch_op.drop_index(batch_op.f('ix_event_classifications_event_id'))

    op.drop_table('event_classifications')
    # ### end Alembic commands ###
