"""add event just culture analysis

Revision ID: 84a7721d5080
Revises: 0e2603df2e8d
Create Date: 2026-09-02 15:50:47.752199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84a7721d5080'
down_revision: Union[str, Sequence[str], None] = '0e2603df2e8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_just_culture_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('tree_version_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_node_code', sa.String(length=50), nullable=True),
    sa.Column('conclusion_code', sa.String(length=100), nullable=True),
    sa.Column('conclusion_label', sa.String(length=500), nullable=True),
    sa.Column('recommendation_code', sa.String(length=100), nullable=True),
    sa.Column('recommendation_label', sa.String(length=500), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['tree_version_id'], ['just_culture_tree_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_just_culture_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_just_culture_analyses_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_event_just_culture_analyses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_just_culture_analyses_tree_version_id'), ['tree_version_id'], unique=False)

    op.create_table('event_just_culture_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('node_code', sa.String(length=50), nullable=False),
    sa.Column('question_text', sa.String(length=2000), nullable=False),
    sa.Column('answer_label', sa.String(length=250), nullable=False),
    sa.Column('target_node_code', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['event_just_culture_analyses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id', 'step_order', name='uq_event_just_culture_answer_step')
    )
    with op.batch_alter_table('event_just_culture_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_just_culture_answers_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_just_culture_answers_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_just_culture_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_just_culture_answers_id'))
        batch_op.drop_index(batch_op.f('ix_event_just_culture_answers_analysis_id'))

    op.drop_table('event_just_culture_answers')
    with op.batch_alter_table('event_just_culture_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_just_culture_analyses_tree_version_id'))
        batch_op.drop_index(batch_op.f('ix_event_just_culture_analyses_id'))
        batch_op.drop_index(batch_op.f('ix_event_just_culture_analyses_event_id'))

    op.drop_table('event_just_culture_analyses')
    # ### end Alembic commands ###
