"""add just culture tree

Revision ID: a6065324834c
Revises: 637aa92ef332
Create Date: 2026-09-02 14:43:38.742224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6065324834c'
down_revision: Union[str, Sequence[str], None] = '637aa92ef332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('just_culture_tree_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('source_title', sa.String(length=500), nullable=True),
    sa.Column('source_author', sa.String(length=250), nullable=True),
    sa.Column('source_organization', sa.String(length=250), nullable=True),
    sa.Column('source_reference', sa.String(length=1000), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('just_culture_tree_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_just_culture_tree_versions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_just_culture_tree_versions_id'), ['id'], unique=False)

    op.create_table('just_culture_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tree_version_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('text', sa.String(length=2000), nullable=False),
    sa.Column('node_type', sa.String(length=30), nullable=False),
    sa.Column('conclusion_code', sa.String(length=100), nullable=True),
    sa.Column('conclusion_label', sa.String(length=500), nullable=True),
    sa.Column('recommendation_code', sa.String(length=100), nullable=True),
    sa.Column('recommendation_label', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tree_version_id'], ['just_culture_tree_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tree_version_id', 'code', name='uq_just_culture_node_version_code')
    )
    with op.batch_alter_table('just_culture_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_just_culture_nodes_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_just_culture_nodes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_just_culture_nodes_tree_version_id'), ['tree_version_id'], unique=False)

    op.create_table('just_culture_transitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_node_id', sa.Integer(), nullable=False),
    sa.Column('answer_label', sa.String(length=250), nullable=False),
    sa.Column('target_node_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_node_id'], ['just_culture_nodes.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['just_culture_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('just_culture_transitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_just_culture_transitions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_just_culture_transitions_source_node_id'), ['source_node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_just_culture_transitions_target_node_id'), ['target_node_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('just_culture_transitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_just_culture_transitions_target_node_id'))
        batch_op.drop_index(batch_op.f('ix_just_culture_transitions_source_node_id'))
        batch_op.drop_index(batch_op.f('ix_just_culture_transitions_id'))

    op.drop_table('just_culture_transitions')
    with op.batch_alter_table('just_culture_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_just_culture_nodes_tree_version_id'))
        batch_op.drop_index(batch_op.f('ix_just_culture_nodes_id'))
        batch_op.drop_index(batch_op.f('ix_just_culture_nodes_code'))

    op.drop_table('just_culture_nodes')
    with op.batch_alter_table('just_culture_tree_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_just_culture_tree_versions_id'))
        batch_op.drop_index(batch_op.f('ix_just_culture_tree_versions_code'))

    op.drop_table('just_culture_tree_versions')
    # ### end Alembic commands ###
