"""add event cause tree

Revision ID: d73ec9d1ef7a
Revises: 84a7721d5080
Create Date: 2026-09-02 16:35:20.001575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd73ec9d1ef7a'
down_revision: Union[str, Sequence[str], None] = '84a7721d5080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_cause_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('fact_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_cause_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_cause_facts_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_cause_facts_id'), ['id'], unique=False)

    op.create_table('event_cause_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('cause_fact_id', sa.Integer(), nullable=False),
    sa.Column('effect_fact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cause_fact_id'], ['event_cause_facts.id'], ),
    sa.ForeignKeyConstraint(['effect_fact_id'], ['event_cause_facts.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cause_fact_id', 'effect_fact_id', name='uq_event_cause_relation')
    )
    with op.batch_alter_table('event_cause_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_cause_relations_cause_fact_id'), ['cause_fact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_cause_relations_effect_fact_id'), ['effect_fact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_cause_relations_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_cause_relations_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_cause_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_cause_relations_id'))
        batch_op.drop_index(batch_op.f('ix_event_cause_relations_event_id'))
        batch_op.drop_index(batch_op.f('ix_event_cause_relations_effect_fact_id'))
        batch_op.drop_index(batch_op.f('ix_event_cause_relations_cause_fact_id'))

    op.drop_table('event_cause_relations')
    with op.batch_alter_table('event_cause_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_cause_facts_id'))
        batch_op.drop_index(batch_op.f('ix_event_cause_facts_event_id'))

    op.drop_table('event_cause_facts')
    # ### end Alembic commands ###
