"""add serious accident criteria

Revision ID: e43c1ad31e12
Revises: 480539a390dc
Create Date: 2026-09-01 12:22:57.860614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e43c1ad31e12'
down_revision: Union[str, Sequence[str], None] = '480539a390dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serious_accident_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criterion_group', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('serious_accident_criteria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_serious_accident_criteria_criterion_group'), ['criterion_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_serious_accident_criteria_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serious_accident_criteria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_serious_accident_criteria_id'))
        batch_op.drop_index(batch_op.f('ix_serious_accident_criteria_criterion_group'))

    op.drop_table('serious_accident_criteria')
    # ### end Alembic commands ###
