"""add event code reference import metadata

Revision ID: eb3c860ae576
Revises: 79e96ce6eb08
Create Date: 2026-08-28 11:27:39.199537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb3c860ae576'
down_revision: Union[str, Sequence[str], None] = '79e96ce6eb08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_code_references', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_version', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('imported_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_code_references', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('imported_at')
        batch_op.drop_column('source_version')

    # ### end Alembic commands ###
