"""add just culture translations

Revision ID: f275e3356aea
Revises: 6a40f409c96c
Create Date: 2026-09-17 14:24:51.592076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f275e3356aea'
down_revision: Union[str, Sequence[str], None] = '6a40f409c96c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('project_manager',
               existing_type=sa.TEXT(),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('site_supervisor',
               existing_type=sa.TEXT(),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('person_category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.alter_column('victim_last_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('victim_first_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('material_damage_details',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('material_damage_cost',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('environmental_damage_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('environmental_damage_details',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('environmental_quantity',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('environmental_unit',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=True)

    with op.batch_alter_table('just_culture_nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_nl', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('text_en', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('conclusion_label_nl', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('conclusion_label_en', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('recommendation_label_nl', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('recommendation_label_en', sa.String(length=500), nullable=True))

    with op.batch_alter_table('just_culture_transitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('answer_label_nl', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('answer_label_en', sa.String(length=250), nullable=True))

    with op.batch_alter_table('just_culture_tree_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_nl', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('name_en', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('description_nl', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('description_en', sa.String(length=2000), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('just_culture_transitions', schema=None) as batch_op:
        batch_op.drop_column('answer_label_en')
        batch_op.drop_column('answer_label_nl')
        batch_op.drop_column('answer_code')

    with op.batch_alter_table('just_culture_nodes', schema=None) as batch_op:
        batch_op.drop_column('recommendation_label_en')
        batch_op.drop_column('recommendation_label_nl')
        batch_op.drop_column('conclusion_label_en')
        batch_op.drop_column('conclusion_label_nl')
        batch_op.drop_column('text_en')
        batch_op.drop_column('text_nl')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('environmental_unit',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('environmental_quantity',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('environmental_damage_details',
               existing_type=sa.String(length=2000),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('environmental_damage_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('material_damage_cost',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('material_damage_details',
               existing_type=sa.String(length=2000),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('victim_first_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('victim_last_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('person_category',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('site_supervisor',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('project_manager',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
